### ISSUE TITLE
docs: document about which algorithms support `length` option for stdCrypto.digest

### ISSUE THREAD

**Issue by kt3k** [denoland/std#1429]
related: https://github.com/denoland/deno_std/pull/1386

**Comment by iuioiua** [comment]
@kt3k, I believe this can be closed.

**Comment by lino-levan** [comment]
@iuioiua The bug has been fixed but the docs have not been changed. 

@kt3k How should this be documented? Is this just a JSDoc comment?

**Comment by kt3k** [comment]
Let's document in JSDoc comment. I also think it's better to document when `length` is meaningful. Do all digest algorithms respect length property? (I guess no)
