### ISSUE TITLE
`FakeTime.runMicrotasks` unmocks globals inside async functions

### ISSUE THREAD

**Issue by arseneyr** [denoland/std#2349]
**Describe the bug**

When mocking time using `FakeTime` and running async functions with `FakeTime.runMicrotasks()` (or `tickAsync()`, `nextAsync()`, `runAllAsync()`), the mocked globals (Date, setTimeout, etc.) are unmocked inside of the async function.

**Steps to Reproduce**

Run `deno test` on the following file:
```ts
import { FakeTime } from 'https://deno.land/x/std@0.143.0/testing/time.ts'
import { assertEquals } from 'https://deno.land/x/std@0.143.0/testing/asserts.ts'

Deno.test("unmocked globals", async () => {
  const time = new FakeTime();
  const FakeDate = Date;
  (async () => {
    assertEquals(Date, FakeDate); // This is run synchronously and is ok
    await 0;
    assertEquals(Date, FakeDate); // Date is unmocked inside the microtask and so the assert fails
  })();
  await time.runMicrotasks();
  time.restore();
});

```
**Expected behavior**

The time globals are mocked throughout the async function.

**Environment**

- OS: Ubuntu under Windows 10 WSL2
- deno version: 1.22.2
- std version: 0.143.0

**Root Cause**

`runMicrotasks()` is implemented by calling `FakeTime.delay(0)`, which itself calls `restoreFor()`:
https://github.com/denoland/deno_std/blob/d1eeb6c8fd3027c28f33ca94d2825ba0d070fb41/testing/time.ts#L382-L383

However, `restoreFor()` calls `await` while globals are unmocked:
```ts
  static async restoreFor<T>(
    // deno-lint-ignore no-explicit-any
    callback: (...args: any[]) => Promise<T> | T,
    // deno-lint-ignore no-explicit-any
    ...args: any[]
  ): Promise<T> {
    if (!time) throw new TimeError("no fake time");
    let result: T;
    restoreGlobals(); // globals unmocked here
    try {

// await queues a new microtask and runs all previously-queued microtasks with globals unmocked

      result = await callback.apply(null, args);
    } finally {
      overrideGlobals();
    }
    return result;
  }
```
**Potential Fixes**

Either convert `restoreFor()` to sync or create a new `restoreForSync()` function and use that inside of `FakeTime.delay()`. I can submit a PR with one of these fixes if you'd like.

**Comment by Milly** [comment]
This may have been closed by #3531.
