### ISSUE TITLE
Wrap an emitter as an async iterable iterator

### ISSUE THREAD

**Issue by harrysolovay** [denoland/std#2367]
**Describe the feature you'd like**

I'm working with a simple subscription method, which accepts a callback and returns the unsubscribe function. Whenever incoming messages arrive, the callback is triggered.

```ts
const unsubscribe = client.subscribe((message) => {
  // use message here
})
```

Nothing too wild going on here.

I'd like a standard approach with which I can manage and iterate over this subscription as an async iterable. Perhaps something like the following.

```ts
import { toAsyncIterableIterator } from "https://deno.land/std@0.144.0/<the-dir>/<the-file>.ts";

const iterable = toAsyncIterableIterator((push) => {
  return client.subscribe((message) => {
    push(message)
  });
});

for await (const message of iterable) {
  // use message here
}
```

`toAsyncIterableIterator` accepts a function, which initializes the subscription / returns the unsubscribe. The `toAsyncIterableIterator`-supplied function accepts a `push` function, which can be utilized in the subscription callback to queue up messages for iteration.

Imo, something like this would make for a wonderful addition to the std lib.

There are a few questions:

- Where does the subscription begin? Upon calling `toAsyncIterableIterator` or upon `for await`ing.
- Does breaking out of the loop end the underlying subscription subscription?
- Would subsequent iteration over `iterable` re-start the subscription?

**Describe alternatives you've considered**

Something along the following lines:

```ts
import { deferred } from "../_deps/async.ts";
import { subscribe, StopListening, Message } from "./subscription.ts";

export class Subscription<Method extends M.SubscriptionMethodName>
  implements AsyncIterableIterator<Message>
{
  #queue: M.NotifMessage<Method>[] = [];
  #cbs: ((value: IteratorYieldResult<Message>) => void)[] = [];
  #stop?: StopListening;

  #start = async () => {
    this.#stop = subscribe((message) => {
      const cb = this.#cbs.shift();
      if (cb) {
        cb({ done: false, value: message });
      } else {
        this.#queue.push(message);
      }
    });
  };

  async next(): Promise<IteratorResult<Message, void>> {
    if (!this.#stop) {
      await this.#start();
    }
    if (this.#queue.length) {
      return {
        done: false,
        value: this.#queue.shift()!,
      };
    }
    const pending = deferred<IteratorYieldResult<Message>>();
    this.#cbs.push(pending.resolve);
    return pending;
  }

  async return(): Promise<IteratorReturnResult<void>> {
    this.#stop!();
    this.#stop = undefined;
    return {
      done: true,
      value: undefined,
    };
  }

  [Symbol.asyncIterator]() {
    return this;
  }
}
```

**Comment by iuioiua** [comment]
Closing as stale. If you're still strongly in favor of having this, please feel free to re-open and try to gather more community feedback. Either way, thank you for the suggestion.
