### ISSUE TITLE
[std/dotenv] - .env.example file is not validated

### ISSUE THREAD

**Issue by cknight** [denoland/std#3555]
**Describe the bug**
If I have a .env.example file as follows:
```sh
# .env.example
SOME_KEY
```
dotenv will not enforce the SOME_KEY env variable is present in the environment (the correct syntax is `SOME_KEY=`).  Indeed, this key is ignored. This seems like an easy mistake to make, especially for beginners.  However, I wonder if allowing multi-line entries makes this to difficult to catch?

**Steps to Reproduce**

1. Create a `.env.example` file with the following contents:
```sh
SOME_KEY
```
2. Assuming there is a mod.ts, run:
```sh
deno run -A mod.ts
```
mod.ts runs without issue.

**Expected behavior**

dotenv validates the content of .env.example and throws an exception on invalid format

**Environment**
- deno version: 1.36.1
- std version: 0.198.0

Perhaps .env.example could be more strictly parsed to catch this?

**Comment by iuioiua** [comment]
We've now removed the `examplePath` option from `@std/dotenv/load`. See #5449 for details. Either way, thank you for your suggestion.
