### ISSUE TITLE
[std/dotenv] - change .env.example to .env.required

### ISSUE THREAD

**Issue by cknight** [denoland/std#3561]
The dotenv module has the concept of a `.env.example` file which dictates a set of environment variables which must be present (either through `.env`/`.env.default` files or via the process environment).  If any are missing after the dotenv is loaded then an exception is thrown.  A secondary use case is that it can be used to document the purpose of these environment variables.  I propose renaming `.env.example` to `.env.required` to be clearer as to its purpose.  'Example' does not convey that the entries are required to exist.

**Comment by iuioiua** [comment]
We've now removed the `examplePath` option from `@std/dotenv/load`. See #5449 for details. Either way, thank you for your suggestion.
