### ISSUE TITLE
todo: complete documentation for `cli/parse_args.ts`

### ISSUE THREAD

**Issue by iuioiua** [denoland/std#4126]
Such that `deno doc --lint cli/parse_args.ts` doesn't report any errors. I made this issue as this task might be quite involved. Familiarity with the API is recommended, especially if referenced types are to be exported.

Towards #3764

**Comment by ngdangtu-vn** [comment]
Since we may have change for `cli` module, maybe we should put this on hold until the #4272 is resolved?

**Comment by iuioiua** [comment]
Completed in #4815.
