### ISSUE TITLE
Add option to prepend `export ` to dotenv stringify

### ISSUE THREAD

**Issue by bombillazo** [denoland/std#4251]
**Is your feature request related to a problem? Please describe.**

Currently, dotenv.stringify only creates Key-Value pair entries into a .env file. Sometimes we need to have the `export ` keyword present in the .env file values

**Describe the solution you'd like**

Add an optional parameter to dotenv.stringify to enable this feature:
```ts
dotenv.stringify({ VALUE: 'My_Value!" }, { prefixExport: true });

// result .env
export VALUE=My_Value!
```

**Describe alternatives you've considered**

Manually editing the resulting file and appending the string... :/

**Comment by jsejcksn** [comment]
> **Describe alternatives you've considered**
> 
> Manually editing the resulting file and appending the string... :/

@bombillazo You don't have to manually edit the file. Unless a breaking change in [the implementation](https://github.com/denoland/deno_std/blob/0.214.0/dotenv/stringify.ts) happens, you can automate this by transforming before writing the file:

```ts
const obj = { FOO: "hello", BAR: "world" };

const dotEnvString = dotenv
  .stringify(obj)
  // Prefix each line with "export "
  .split("\n")
  .map((s) => `export ${s}`)
  .join("\n");

console.log(dotEnvString === "export FOO=hello\nexport BAR=world"); // true

// Write to file…
```

[TS Playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&removeComments=true&target=99&jsx=4&exactOptionalPropertyTypes=true&inlineSourceMap=true&inlineSources=true&isolatedModules=true&noImplicitOverride=true&noErrorTruncation=true&ssl=39&ssc=1&pln=42&pc=1#code/MYewdgzgLgBAJiKBTMA3GBeGAKbBKTAPhgG8AoASAHoqYALKKABwgC4aBzASyjoFcARgDpQAWypwUIADYBDMHAlSA+tEUDpIAVQAMQgEwBGACxCdExClRVoAJy5huAMwCeQqBEpO+YYFC7gMHYOzi7YWgBWSH6sMABK0SC2cAA8wY4ANEFQ9o6EeLHpHKSUFKCQsNIOSGzZuRwA2gC6mDDNANylTkk45dBtANZILlmostJ8SC0gTjAA8gJRfkIoOVw14YvRUHgE5BQH0kiwAI58lp0HFEewNcCyTEhwAGrjk61jE0gwAPw-MAAiAGXA5cWbYIZuaCyWweADqPDo2ABAGIAbsSlcyuAIDIkEIAO4wsDYUpXAAGkOyMI8MAJiJgshgAHIUcyYA44Fx7sgIIyYGJRKtGQoOXyuBwwEknrFmQASEiQgC+zPJGTJFDwIIO5X8YEm2qVMCQ0gg3zBODuDyery+QgcwAmkggyIAOmB0XsNVbHi83t8sD6bf6hLYkEw5MAkABBaTSN0erIA13u9HaihnSytckA8mG42m83goN+u2iWRQYBIqiuuFUDH7K6Z5CtAHM4FkpVki3YZtIL1Yku296BiD3X3D-FhiOyKOx+N9rLklMKvtK8la71j62lkcwcmr87IJUKof+k8kNd5ztkvqVarZhXKjCn7cT8-Xq5VMA1IRMPgQEi379iCXYHGGUB8LYYAwMBEBCBEIAOAmaaUGBEFQTBJB1CEYIuDASqdEqeD4J0ZB3jAkStNhABicxzLEAJ0CamgAlkABC0ZxIxBJJNIcAAgRZEUQgUAAKJoAAymsjitKJViUEIRR4ZsER4IpEARjwKHqRQQjlkwuAQAQGDEOSSAAB5MEksAKhA666QhSEksmHqbuROJ4kImgcNgokSag0n1JgGBYAClnWbCMB0XMGDMXGIDuhFNkwJxcQYLxtj8WmMA0DAOSTGQZB5XC9gtlAIAwE4XBHIAZARkEAA)

**Comment by timreichen** [comment]
I think this would be a good addition.
But there are multiple ways to go about this and also some problems when arguing that `parse()` and `stringify()` should be exact opposite functions that reverse each step exactly.

Adding an option which takes a list of exported keys:
```ts
stringify({ FOO: "bar" }, { exports: ["FOO"] })
```
or adding an `export` property:
```ts
stringify({ FOO: { value: "bar", export: true } })
```

For an exact reversal function, the current `parse()` implementation is inadequately designed because it is lossy. It doesn't distinguish between exported and non-exported keys.

So the reversal would mean either
```ts
const { data, exports } = parse("export FOO=bar")
// data: { FOO: "bar" }
// exports: ["FOO"]
```
or
```ts
const data = parse("export FOO=bar")
// data: { FOO: { value: "bar", export: true }
```

Imo the second approach is better. That would also mean a breaking change in the dotenv API.

**Comment by bombillazo** [comment]
Those are nice considerations. Perhaps another separate method can be added for this advanced parsing/stringifying?

I think the current API is very convenient, simple, and sweet for most cases. I'm not sure about the Deno convention for these types of enhanced methods, but forcing the more complex response as the default may make the API usage more verbose and complicated.

**Comment by bombillazo** [comment]
@jsejcksn Hey! Thats exactly how we are currently handling this. It works and one has complete control on which functions to export or not in the map function. :)

**Comment by iuioiua** [comment]
I think the solution provided in [this comment](https://github.com/denoland/std/issues/4251#issuecomment-1924713752) is right and is easily done by any user that wants this result. However, I don't think there's sufficient demand to extend the functionality of `parse()` and `stringify()` in `@std/dotenv`. I think that's best that we keep these functions simple.

Closing this issue now. If there are any strong opinions, we can re-open. Thanks everyone.
