### ISSUE TITLE
suggestion(semver): remove redundant `increment()` arguments

### ISSUE THREAD

**Issue by timreichen** [denoland/std#4420]
**Is your feature request related to a problem? Please describe.**

`increment()` has four arguments (two required, two optional). That is more than the [style guide](https://docs.deno.com/runtime/manual/references/contributing/style_guide#exported-functions-max-2-args-put-the-rest-into-an-options-object) suggests.
- `buildmetadata` just seem to replace the semver build property.
- `prerelease` as a string kinda breaks the established pattern of prerelease being an `(string|number)[]` array and needs to be parsed inside `increment()`. It doesn't seem very intuitive, how that argument works in combination with `ReturnType` and existing `version.prerelease`.  This is why the majority of the jsdoc description tries to explain that.

**Describe the solution you'd like**

- Remove `buildmetadata` argument, as `version.build` can be set outside the `increment()` function.
- Remove `prerelease ` argument, as `version.prerelease` can be set outside the `increment()` function.

**Describe alternatives you've considered**

Leave as is.

**Comment by iuioiua** [comment]
I'm for this. @kt3k?

**Comment by kt3k** [comment]
I'm not in favor.

Without `prerelease` option, the release type of `premajor`, `preminor`, `prepatch` doesn't make sense. (You can't increment from `0.1.0` to `1.0.0-rc.1`, for example, without `prerelease` option).

**Comment by iuioiua** [comment]
Oh, I see—my misunderstanding. I think we should at least put these two arguments into an optional last argument to adhere to our style guide.
