### ISSUE TITLE
chore: improve the output of `_tools/check_circular_package_dependencies.ts`

### ISSUE THREAD

**Issue by kt3k** [denoland/std#4656]
https://github.com/denoland/deno_std/pull/4653#issuecomment-2082028623

Better to have more specific output like:
```
Circular dependencies found: fs/copy -> path/basename -> fs/copy
```

**Comment by iuioiua** [comment]
@kt3k, seems like we might not need this that much. It hasn't been an issue since that one time.

**Comment by kt3k** [comment]
Agree. Let's close
