### ISSUE TITLE
chore: setup new release process

### ISSUE THREAD

**Issue by kt3k** [denoland/std#4673]
related #4600 

Now we stop publishing all packages in cadence, but we only publish packages which have relevant changes during certain amount of time.

We use https://github.com/denoland/bump-workspaces for performing this pattern of updating.

**Comment by iuioiua** [comment]
Is there anything to action here?

**Comment by kt3k** [comment]
I think it's completed now.

Let's open new issues if we need to add anything to the release process.

**Comment by inverted-capital** [comment]
Is all the code that was previously used for this cleaned out of this repository ?

The `release` folder appears to have been superseded and should be deleted ?

https://github.com/denoland/std/tree/main/_tools/release
