### ISSUE TITLE
ini file parsing considers all values as strings

### ISSUE THREAD

**Issue by dsherret** [denoland/std#4806]
**Describe the bug**

**Steps to Reproduce**

```
> import { parse } from "jsr:@std/ini"
undefined
> parse("value=undefined")
{ value: "undefined" }
> parse("value=null")
{ value: "null" }
> parse("value=true")
{ value: "true" }
> parse("value=false")
{ value: "false" }
> parse("value=123")
{ value: "123" }
```

**Expected behavior**

Should understand booleans, undefined, null, and numbers.

**Environment**

- OS: [e.g. Ubuntu 20.04, MacOS 11]
- deno version:
- std version: 0.224.0

**Comment by kt3k** [comment]
Looks like supporting boolean, number, string is common among parsers https://en.wikipedia.org/wiki/INI_file#Comparison_of_INI_parsers
