### ISSUE TITLE
semver: `parseRange` doesn't throw with invalid input

### ISSUE THREAD

**Issue by kt3k** [denoland/std#4845]
The below example doesn't throw a type error:

```ts
import { parseRange } from "@std/semver";
const range = parseRange("invalid");
console.log(range);
```

Instead it prints the below range object:
```js
[
  [
    {
      operator: "<",
      major: 0,
      minor: 0,
      patch: 0,
      prerelease: [],
      build: []
    }
  ]
]
```

**Comment by JakeAve** [comment]
I've been looking at this and we can update it, but it makes another test case fail. How does this relate to the test case on `semver/parse_range_test.ts` line 354: 

```
    ["blerg", [
      [
        {
          operator: "<",
          major: 0,
          minor: 0,
          patch: 0,
          prerelease: [],
          build: [],
        },
      ],
    ]],
```

**Comment by iuioiua** [comment]
Yes, that's expected. We'd have to tweak the `parseRange() parse ranges of different kinds` test to recognize thrown errors.

**Comment by kt3k** [comment]
I think `parseRange('blerg')` should throw

**Comment by iuioiua** [comment]
Clarifying my previous message, I meant changing tests is to be expected. I'm in agreement that `parseRange("blerg")` should throw.
