### ISSUE TITLE
suggestion: add base32hex to encoding

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/std#4917]
Since the [spec](https://www.rfc-editor.org/rfc/rfc4648.html) for [`@std/encoding`](https://jsr.io/@std/encoding) specifies a [base32hex](https://www.rfc-editor.org/rfc/rfc4648.html#section-7) format, I think it would be reasonable to also include this variation in the [`@std/encoding`](https://jsr.io/@std/encoding) lib. The only difference between [base32hex](https://www.rfc-editor.org/rfc/rfc4648.html#section-7) and [base32](https://www.rfc-editor.org/rfc/rfc4648.html#section-6) is the alphabet used.

**Comment by 91pornaaaaa** [comment]
https://91porna.com/

**Comment by BenMcLean981** [comment]
I think I have this working in my forked copy. Will create a PR soon.
