### ISSUE TITLE
stabilize `@std/url`

### ISSUE THREAD

**Issue by kt3k** [denoland/std#4924]
part of #4600 

- [x] fully documented
- [x] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

**Comment by 91pornaaaaa** [comment]
https://91porna.com/

**Comment by iuioiua** [comment]
Blocker: #4967

**Comment by kt3k** [comment]
Probably we are not stabilizing this package. ref #4992 

Instead we explore alternative solution to solve the issues which `std/url` was supposed to solve
