### ISSUE TITLE
assertNotEquals assertion error message discrepancy

### ISSUE THREAD

**Issue by se-u** [denoland/std#4955]
There is an issue with the `assertNotEquals` output int the current version of the library. The assertion error message does not reflect the expected string values accurately. Specifically, the following test case:

`assertNotEquals('1','1');`

is expected to throw an error with the message:

`AssertionError: Expected actual: '1' not to be: '1'.`

However, the current output is:
`AssertionError: Expected actual: 1 not to be: 1.`

**Environment**

- OS: MacOS 12
- deno version: 1.44.0
- std version: 0.226.0

**Comment by iuioiua** [comment]
I'm happy to add quotes to strings for this function. WDYT, @kt3k?
