### ISSUE TITLE
stabilize `@std/io`

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5003]
part of #4600 

- [ ] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

**Comment by iuioiua** [comment]
Closing as we are no longer stabilizing `@std/io`. This is to nudge people to use `@std/streams` instead. We'll soon create an issue that goes into more detail.
