### ISSUE TITLE
stabilize `@std/streams`

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5004]
part of #4600 

- [x] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

**Comment by iuioiua** [comment]
We should address https://github.com/denoland/std/pull/5079#issuecomment-2238102750 before proceeding with the stabilization.
