### ISSUE TITLE
stabilize `@std/http`

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5007]
part of #4600 

- [x] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

**Comment by iuioiua** [comment]
Note: We are making an exception of stabilizing `@std/http` even though a dependency, `@std/net`, is not yet stable.

**Comment by kt3k** [comment]
file-server apparently has low coverage number. That is because we currently can't get the coverage data of CLI entrypoint. That can be improved when Deno supports https://github.com/denoland/deno/issues/23961
