### ISSUE TITLE
stabilize `@std/fs`

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5008]
part of #4600 

- [ ] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

**Comment by phaux** [comment]
Can #1102 be revisited before stabilization? particularly the change described in https://github.com/denoland/deno_std/issues/1102#issuecomment-893623153

**Comment by kt3k** [comment]
> Can https://github.com/denoland/deno_std/issues/1102 be revisited before stabilization? particularly the change described in https://github.com/denoland/deno_std/issues/1102#issuecomment-893623153

Sounds reasonable to me

**Comment by kt3k** [comment]
@phaux See the comment at https://github.com/denoland/deno_std/issues/1102#issuecomment-2205902843 The scenarios there are already covered by `expandGlob(Sync)`. Please use those APIs instead.
