### ISSUE TITLE
stabilize `@std/dotenv`

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5018]
part of #4600 

- [ ] fully documented
- [ ] fully tested
- [x] no ongoing breaking change discussion
- [ ] 1.0.0-rc.1
- [ ] wait 1 month
- [ ] 1.0.0 (stabilization)

**Comment by iuioiua** [comment]
After discussions with Yoshiya, we've decided to not stabilize `@std/dotenv`, as it has overlap with Deno's `--env-file` flag. However, `@std/dotenv` does provide the ability to load `.env` files at runtime for compiled scripts (compiled using [`deno compile`](https://docs.deno.com/runtime/manual/tools/compiler/)). `--env-file` doesn't have this ability. So, while the stability of `@std/dotenv` **could** change in  the future. Either way, closing as unplanned for now.
