### ISSUE TITLE
msgpack: non-string/non-number key supprt

### ISSUE THREAD

**Issue by mfulton26** [denoland/std#5021]
I could be reading is spec wrong but it looks to me like Map keys should support and supported value and not only strings and numbers. If so, it might be helpful to use JS `Map` instances instead of objects.

https://github.com/denoland/deno_std/blob/36b4182728fde467ade8ce8f251f55b6aee73c84/msgpack/mod.ts#L41

**Comment by iuioiua** [comment]
To be frank, I think you're reading the spec wrong 😅
It says that keys can be strings or numbers, and values can be any of the other values (i.e. `bigint`, `Uint8Array`, etc.)

Either way, thank you for aiming to clarify. Closing this as there's nothing to action.
