### ISSUE TITLE
feature request(streams):  lines(readable): AsyncIterable<string>

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5071]
Idea from some discussion: A quick helper for getting an async iterable (or maybe another stream) of lines from a ReadableStream.

Example signature: `lines(readable: ReadableStream<Uint8Array>|ReadableStream<string>): AsyncIterable<string>`

```ts
import { lines } from "@std/streams";

const file = await Deno.open(filename);
for await (const line of lines(file.readable)) {
  console.log(line);
}
```

**Comment by BlackAsLight** [comment]
Does this not already exist via [`TextLineStream`](https://jsr.io/@std/streams/doc/~/TextLineStream)?
```ts
import { TextLineStream } from '@std/streams'

for await (
  const line of (await Deno.open())
    .readable
    .pipeThrough(new TextEncoderStream())
    .pipeThrough(new TextLineStream())
)
  console.log(line)
```

**Comment by iuioiua** [comment]
I'm impartial to adding this. The above code snippet using `TextLineStream()` seems to suffice.

**Comment by kt3k** [comment]
> ```ts
> import { TextLineStream } from '@std/streams'
> 
> for await (
>   const line of (await Deno.open('./deno.json'))
>     .readable
>     .pipeThrough(new TextEncoderStream())
>     .pipeThrough(new TextLineStream())
> )
>   console.log(line)
> ```

The above example is correct, but it looks a bit cluttered for such typical simple task, compared to other languages/runtimes.

Reading lines from a file is much simpler in other languages.

python
```py
file = open('README.md', 'r')
for line in file.readlines():
  print(line)
```

perl
```pl
open(INFO, "README.md") or die();
foreach $line (<INFO>)  {   
  print $line;    
}
```

I think it would be useful to have special/ergonomic wrapper for such typical task

**Comment by BlackAsLight** [comment]
If something like this is to be added, I think a `toLines(stream)` to align with `toText` and `toJSON` would be best. Although on the other hand somebody might assume it would return an iterable of strings instead of an async iterable of strings.

**Comment by kt3k** [comment]
`toLines` sounds good to me

**Comment by jsejcksn** [comment]
I agree with the [comment](https://github.com/denoland/deno_std/issues/5071#issuecomment-2175314512) by @iuioiua — this seems convenient, but also somewhat trivial.

If it is decided to be added, I think that the return type should be `ReadableStream<string>` to provide more convenience value: it already [implements](https://deno.land/api@v1.44.4?s=ReadableStream#method__Symbol_asyncIterator__7) `AsyncIterable<string>` and can also be piped, etc.
