### ISSUE TITLE
text: Add `algorithm` option to string comparison functions

### ISSUE THREAD

**Issue by RuiNtD** [denoland/std#5111]
**Is your feature request related to a problem? Please describe.**

Currently, the string comparison functions in the `text` module (such as `wordSimilaritySort`) are hard coded to use Levenshtein distance, with a note saying "this metric may change in future versions", which could potentially break projects expecting consistent results.

**Describe the solution you'd like**

An added option (similar to `caseSensitive`) in these functions for the user to provide their own algorithm, which could also be passed the already exported `levenshteinDistance` function. These functions could, like before, default to whatever algorithm Deno recommends (currently Levenshtein).

```ts
/** Options for {@linkcode compareSimilarity}. */
export interface CompareSimilarityOptions {
  /**
   * Whether the distance should include case.
   *
   * @default {false}
   */
  caseSensitive?: boolean;
  /**
  * Function used to compare two strings.
  * Lower number means closer match.
  * 0 means numbers match.
  * 
  * @default {@linkcode levenshteinDistance}
  */
  algorithm?: (str1: string, str2: string) => number;
}
```

**Describe alternatives you've considered**

**Comment by iuioiua** [comment]
Good idea. PRs are welcome!

**Comment by RuiNtD** [comment]
Can probably work on this tonight or tomorrow. Any changes I should make to the proposed documentation or variable name?

**Comment by iuioiua** [comment]
Thanks! Your proposed documentation LGTM.

**Comment by RuiNtD** [comment]
Would it make sense to export a `getWordDistance` function in `text` as well, so that Deno's current "recommended" algorithm is exported, if ever changed?

**Comment by iuioiua** [comment]
Completed in #5448. Thank you for your suggestion and PR, @RuiNtD.
