### ISSUE TITLE
to-do: add missing `@std/yaml` options tests

### ISSUE THREAD

**Issue by iuioiua** [denoland/std#5285]
- [x] `ParseOptions.onWarning`
- [x] `ParseOptions.allowDuplicateKeys`

**Comment by kt3k** [comment]
One of onWarning usages is tested here https://github.com/denoland/deno_std/blob/ed1ab2684a945851c54408dc1c9b119a14b1a6c2/yaml/parse_test.ts#L646-L662

We can add similar cases to other warning paths.
