### ISSUE TITLE
suggestion: replace `YamlError` with native errors

### ISSUE THREAD

**Issue by iuioiua** [denoland/std#5340]
Should we split `YamlError` into `ParseError extends SyntaxError` and `StringifyError extends Error` like in csv?

_Originally posted by @timreichen in https://github.com/denoland/deno_std/issues/5328#issuecomment-2212350787_

**Comment by timreichen** [comment]
On that topic: There are two standards now: Throwing native errors (msgpack, jsonc, ini, csv, encoding, semver), and custom errors (dotenv, toml, yaml). 
Maybe we could have all std parse/stringify mods behave the same and therefore more predictably. Shall we get rid of `TOMLError` and `YamlError` completely and replace them with native errors?

**Comment by iuioiua** [comment]
Well, we throw custom errors in `assert`, `async`, `csv`, `dotenv`, `fs`, `io`, `testing`, `toml` and `yaml`. It's a good suggestion, but I'm on the fence. Can you please open an issue with the suggestion? It'd be good to hear other opinions.

**Comment by iuioiua** [comment]
I'm not yet certain that we should use native errors in all cases, but I think we should at least align with [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) and [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) in their exceptions, for packages that parse and stringify. These exceptions are [`SyntaxError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError) and [`TypeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError), respectively.
