### ISSUE TITLE
test(fs): do not write files in source tree during test

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5358]
`std/fs` test cases directly write files in source tree during test. This makes debugging of test cases difficult when they failed in the middle. These test cases should use temp directory instead.

**Comment by jbronder** [comment]
I'd be interested in working through these.  I looked over some of the test files and it looks like `copy_test.ts` and `exists_test.ts` do incorporate making temp directories.  I imagine similar approaches for the other applicable `_test.ts` files.

**Comment by kt3k** [comment]
Thanks!

> I looked over some of the test files and it looks like copy_test.ts and exists_test.ts do incorporate making temp directories. I imagine similar approaches for the other applicable _test.ts files.

Yes, that's correct
