### ISSUE TITLE
Check the usage of TextDecoder

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5384]
There was an error in the usage of TextDecoder as pointed in https://github.com/denoland/deno_std/pull/5381 (`stream: true` wasn't set correctly for streaming data). We need to check if there's any similar mistake in the code base.

**Comment by iuioiua** [comment]
It seems [`archive/untar.ts`](https://github.com/denoland/std/blob/main/archive/untar.ts) and [`msgpack/decode.ts`](https://github.com/denoland/std/blob/main/msgpack/decode.ts) might be using the API in a streaming fashion. Though, more investigation is needed.

Other uses of `TextDecoder` in the codebase are not using it in a streaming fashion, or are deprecated (i.e. `@std/io`).

Feel free to investigate, if I don't get to it first.

**Comment by kt3k** [comment]
> It seems [archive/untar.ts](https://github.com/denoland/std/blob/main/archive/untar.ts) and [msgpack/decode.ts](https://github.com/denoland/std/blob/main/msgpack/decode.ts) might be using the API in a streaming fashion. Though, more investigation is needed.

Both usages seem fine as is (They don't look like decoding chunks, but look decoding some entire value, meta info, etc)

Let's close.
