### ISSUE TITLE
http/file-server, media_types: new addition `application/mp4` to mime db overrides `video/mp4` and breaks some net players

### ISSUE THREAD

**Issue by NaitLee** [denoland/std#5433]
**Describe the bug**
New addition [`application/mp4`](https://github.com/denoland/deno_std/blame/f54eab4355c1def5baa78533fb852bde1c6b761d/media_types/vendor/db.ts#L1049) to `media_types/vendor/db.ts` (#2286) overrides [`video/mp4`](https://github.com/denoland/deno_std/blob/f54eab4355c1def5baa78533fb852bde1c6b761d/media_types/vendor/db.ts#L8597) for the `contentType` function. As `file-server` specifies `content-type` [by that function and the db](https://github.com/denoland/deno_std/blob/f54eab4355c1def5baa78533fb852bde1c6b761d/http/file_server.ts#L234), it breaks some network-capable video players which expecting the mimetype to be `video/*`, because the received mimetype `application/mp4` is unexpected, they won't play the video anymore

**Steps to Reproduce**

1. Start newest `file-server` inside a folder with some mp4
```
$ deno run --allow-read --allow-net --allow-sys jsr:@std/http@1.0.0-rc.4/file-server
Listening on:
- Local: http://localhost:8000
- Network: http://192.168.2.103:8000
```
2. Issue a HEAD request to any video:
```
$ curl --head http://localhost:8000/1.mp4
HTTP/1.1 200 OK
...
content-type: application/mp4
...
```
3. The `content-type` is the new addition `application/mp4`, as it wins `video/mp4`. This breaks some network players as stated, as they don't identify `application/mp4`; they only know about `video/mp4`

**Expected behavior**

1. Start an older version of `file-server`, without the mimetype update
```
$ deno run --allow-read --allow-net --allow-sys jsr:@std/http@0.224.0/file-server
Listening on:
- Local: http://localhost:4507
- Network: http://192.168.2.103:4507
```
2. Issue a HEAD request to any video:
```
$ curl --head http://localhost:4507/1.mp4
HTTP/1.1 200 OK
...
content-type: video/mp4
...
```
3. as the mimetype `video/mp4` is by far the most preferred, it always worked for most (if not all) network players

**Environment**

- OS: any
- deno version: 1.45.2
- std version:
  - `@std/media_types` after the commit 6d58a57a011527c453dc79afc21453be1beb449e
  - `@std/http` 0.224.1 and above

**P.S.**

I think we need a smarter `contentType` function or mimetypes db that has preference over the "best" mimetype for certain file extensions. I see a similar problem had happened on `application/javascript` over `text/javascript` (#5186), probably there are far more media types are affected.

Likely that most players affected by this are proprietary, so fixing all the players is not feasible.

**Comment by iuioiua** [comment]
Thank you for testing `@std/http@1.0.0-rc.4` out. This bug should be addressed before stabilization.

Currently, the value of the content-type header is determined from the extension in the URL. Instead, we should gather all possible content-types for a given extension (i.e. something like a version of `contentType` that returns an array of possible content-types instead of just one), then use [`accepts`](https://jsr.io/@std/http@1.0.0-rc.4/doc/negotiation/~/accepts) to determine the most appropriate content-type, based on the client's request.

Any thoughts, @kitsonk?

**Comment by kt3k** [comment]
Looks like this is affected by this change in the upstream https://github.com/jshttp/mime-db/commit/48e411522aed9925570b6c6bbf0bbc331242c038

**Comment by kt3k** [comment]
@NaitLee Do you know if those players send `accept` headers when requesting mp4 files?

**Comment by kt3k** [comment]
I think we should just return `video/mp4` for `contentType(".mp4")` (and `typeByExtension(".mp4")`) by defining our preference in `media_types/_db.ts`.

**Comment by kt3k** [comment]
See also https://stackoverflow.com/questions/9929940/correct-mime-type-for-mp4

**Comment by NaitLee** [comment]
> @NaitLee Do you know if those players send `accept` headers when requesting mp4 files?

in my test, none of android vlc, mpv, and other numerous players i've tested send `accepts` header.

i'm wondering if `application/x` is always "the least prefered type" if other types like `video/x` or `text/x` are around. if that's the case just prefer those over `application/x` one.

in my mind the preference can be `video > audio > image > text > application`, it's at least correct for mp4, ogg, svg, and javascript, probably ok for `.ts` too.

**Comment by kt3k** [comment]
Looks like there's a line that implements the preference of `application/*` types over other types https://github.com/denoland/std/blob/702f0487f9e970826bda4e08523d2c6edba5475c/media_types/_db.ts#L37


The line exists from the beginning of the package: https://github.com/denoland/std/pull/2286/files#diff-92e0917a6de42a1319f4f29e026ba39b73bf1dc70dececdcbced2d732b018d99R60
