### ISSUE TITLE
feat req (html): add a validator for custom name elements ?

### ISSUE THREAD

**Issue by lowlighter** [denoland/std#5437]
**Is your feature request related to a problem? Please describe.**

I don't know if it's out of scope for the html package, but would it be possible to add a [custom element name](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#name) validator ?

It is defined by the spec https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name as

> PotentialCustomElementName ::= 
> - [a-z] ([PCENChar](https://html.spec.whatwg.org/multipage/custom-elements.html#prod-pcenchar))* '-' ([PCENChar](https://html.spec.whatwg.org/multipage/custom-elements.html#prod-pcenchar))*
>
> PCENChar ::=  
> - "-" | "." | [0-9] | "_" | [a-z] | #xB7 | [#xC0-#xD6] | [#xD8-#xF6] | [#xF8-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x203F-#x2040] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
>
> name must not be any of the following:
> -   annotation-xml
> -   color-profile
> -   font-face
> -   font-face-src
> -   font-face-uri
> -   font-face-format
> -   font-face-name
> -   missing-glyph

Since the spec is unlikely to change often, this is low maintenance and it's something standard.

The gain is that the regex is pretty troublesome to define so people might tempted to implement it themselves and end up with a non-conforming.

**Describe the solution you'd like**

Something similar to https://github.com/mathiasbynens/is-potential-custom-element-name/blob/master/index.js I guess,
but it's missing the list of forbidden names.

**Describe alternatives you've considered**

**Comment by luk3skyw4lker** [comment]
If it's in the HTML spec I don't see why it wouldn't be okay to add it in the package. I don't know what the maintainers think about this but I'm upvoting this to be implemented, if it's okay I can do the work myself.

@kt3k @iuioiua @bartlomieju

**Comment by iuioiua** [comment]
I don't have any objections. Happy to hear other takes.

**Comment by bartlomieju** [comment]
Seems useful, +1 from me

**Comment by iuioiua** [comment]
That's good enough for me. Please feel free to open a PR, @luk3skyw4lker.
