### ISSUE TITLE
Performance: `levenshteinDistance` becomes extremely slow for large edit distances

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/std#5465]
**Describe the bug**

[`levenshteinDistance`](https://github.com/denoland/std/blob/c6998992a332f07cf223c89031eaa554ca6a4e67/text/levenshtein_distance.ts) becomes extremely slow for large edit distances.

**Steps to Reproduce**

```ts
const fmt = (n: number) => n.toLocaleString('en-US').padStart(6)

for (const n of [1_000, 2_000, 3_000, 10_000, 20_000, 30_000]) {
    const start = Date.now()
    levenshteinDistance('a'.repeat(n), 'b'.repeat(n))
    console.log(`Length = ${fmt(n)}: ${fmt(Date.now() - start)} ms`)
}
```

Sample results:

```
Length =  1,000:     39 ms
Length =  2,000:     80 ms
Length =  3,000:    177 ms
Length = 10,000:  2,044 ms
Length = 20,000:  7,865 ms
Length = 30,000: 20,883 ms
```

These performance characteristics are expected given that Levenshtein distance is `O(n * m)` where `n` and `m` are the lengths of the strings, but some way of mitigating the problem is desirable, as it could cause issues such as denial-of-service (whether unintentional or malicious).

**Expected behavior**

Possible options:
1. No change, maybe add a notice to the JSDoc comment for `levenshteinDistance` and the other functions that depend on it.
2. Throw on long inputs. Breaking change and probably not ideal as slow calculation may not be an issue in all use cases.
3. Return a special value for long inputs, such as `NaN`, `Infinity`, `-1`. Of these, `Infinity` is probably the least likely to cause problems, but it'd still be a breaking change... plus it's still less than ideal as `JSON.stringify(Infinity)` gives `'null'`.
4. Return `Math.max(str1.length, str2.length)` for long inputs. Simple and unlikely to cause show-stopping problems, but highly inaccurate for typical inputs.
5. Periodically check time elapsed while the function is executing, then return some value or throw if time elapsed exceeds some threshold. The returned value could be `Math.max(str1.length, str2.length)` or maybe something more accurate using the partial calculation so far as a heuristic. Would probably cause a slight degradation in performance for shorter inputs due to repeated `Date.now()` calls, but hopefully this wouldn't be significant.
6. Use a reduced granularity of edit difference (words? lines?) for longer inputs. Probably not a great option as it's both overly complex and insufficient to prevent malicious denial-of-service — any input that's split into a massive number of very short words/lines would still have the same performance problems.

Currently I'm favoring 5 or 4, maybe with a configurable option for max time elapsed/input length.

**Environment**

- OS: Ubuntu 20.04, WSL
- deno version: 1.45.2
- std version: text@0.224.3

**Comment by 0f-0b** [comment]
I think `levenshteinDistance` should always return the correct result regardless of the size of the inputs, and it should be up to the application to truncate the inputs to a reasonable size when necessary, so I would prefer option 1. Maybe std can adopt a faster algorithm such as the one described in [this paper](https://dl.acm.org/doi/pdf/10.1145/316542.316550) ([a TypeScript implementation](https://github.com/ka-weihe/fastest-levenshtein/blob/29f25a1409e09d703caf6746fa9b3a3230607d91/mod.ts)).

**Comment by timreichen** [comment]
https://github.com/denoland/std/pull/5467#issuecomment-2234114373

**Comment by iuioiua** [comment]
I strongly agree with @0f-0b. Let's hold off on optimizing the function until we receive confirmation that users are comparing strings 1,000s of characters long.

**Comment by lionel-rowe** [comment]
> I strongly agree with @0f-0b. Let's hold off on optimizing the function until we receive confirmation that users are comparing strings 1,000s of characters long.

My concern is less the case of intentionally comparing thousands of chars, more likely is comparing arbitrary text/user input that's expected to be short but actually could be much longer (`textarea` form submission, API request body, `TEXT` column in a database, etc).

**Comment by iuioiua** [comment]
I see. Frankly, we'd prefer to keep APIs simple but sometimes it's worth optimizing if the performance payoff is significant enough. Maybe it is in this case.

I quickly played with the optimized TypeScript implementation suggested by @0f-0b and found it to be 130-140x faster than the current implementation and it passes all tests. So maybe we can go with that. A PR would be welcome, though, with some amendments to compensate for the added complexity and reduced understandability:
1. Clearer variable names.
2. Documentation and inline comments (within reason) explaining the code.
3. Make the TypeScript checker happy.

**Comment by iuioiua** [comment]
Completed in #5527
