### ISSUE TITLE
tracking: support iterables in `@std/collections` APIs

### ISSUE THREAD

**Issue by iuioiua** [denoland/std#5470]
Following on from #4671, it seems there are APIs within `@std/collections` that could support `Iterables` rather than just arrays. From a quick scan, these symbols might be able to be tweaked to support iterables:
- [x] `chunk()`
- [x] `dropLastWhile()`
- [x] `dropWhile()`
- [x] `intersect()`
- [x] `sample()`
- [x] `slidingWindows()`
- [x] `sortBy()`
- [x] `takeLastWhile()`
- [x] `takeWhile()`
- [x] `withoutAll()`

See #3390 for an example of how with was done for `groupBy()`.

**Comment by Liam-Tait** [comment]
A larger change to consider. Should collections use generators? This would be breaking change.

Generators give lazy evaluation, memory efficiency, and sometimes better performance

Example:
```typescript
function* takeWhile<T>(
  iterable: Iterable<T>,
  predicate: (el: T) => boolean,
): Generator<T> {
  for (const element of iterable) {
    console.log(`takeWhile(): ${element}`);
    if (!predicate(element)) {
      break;
    }
    yield element;
  }
}

function* map<T, U>(
  iterable: Iterable<T>,
  transform: (el: T) => U,
): Generator<U> {
  for (const element of iterable) {
    console.log(`map(): ${element}`);
    yield transform(element);
  }
}

const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
const result = takeWhile(map(arr, (n) => n * 100), n => n < 500)
console.log([...result])
```

**Comment by iuioiua** [comment]
I think we should stick to the current approach unless the performance benefits are sufficient. We'd have to measurements before coming to that decision.

**Comment by Liam-Tait** [comment]
The move to iterables means that generators that never return are valid arguments.
```ts
  function* counter() {
    let i = 0;
    while (true) {
      yield i++;
    }
  }
```
Many of these functions would hang

Examples:
```ts
chunk(counter(), 10)
dropLastWhile(counter, v => v > 30)
dropWhile(counter, v => v === 0)
```
Here are some options:
1. Don't handle the case, onus is on the user to know the generator is infinite. Likely case is  throwing an `Uncaught RangeError: Invalid array length`
2. Catch the error an rethrow?
3. Have a max iterations option available

**Comment by Liam-Tait** [comment]
@iuioiua Would you like to assign this to me, I am happy to commit myself to completing all of these changes

**Comment by timreichen** [comment]
I think that is the correct option.

**Comment by Liam-Tait** [comment]
I believe this is now completed (unstable)

**Comment by kt3k** [comment]
@Liam-Tait Thank you for your contributions! Closing as completed
