### ISSUE TITLE
path: make some `@std/path` functions work with file URL object

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5537]
As FS APIs in Deno works with file URL object, it would make sense to support file URL input with `path.dirname`.

```ts
dirname(new URL("file:///path/to/dir/file")) // returns `/path/to/dir` on unix
dirname(new URL("file:///C:/path/to/dir/file")) // returns `C:\path\to\dir` on windows
```

This probably would throw with non-file URLs.

I think this mostly addresses the motivation we added `std/url`.

- [x] `dirname()`
- [x] `extname()`
- [x] `join()`
- [x] `basename`
- [x] `normalize`

**Comment by iuioiua** [comment]
Just `dirname()` or the other functions too?

**Comment by kt3k** [comment]
I think this also makes sense for other functions such as `basename`, `extname`, `common`, `join`, `relative`, and `resolve`

**Comment by kt3k** [comment]
I don't think we need to limit this to `std/path/posix` as file URL object is platform independent

**Comment by kt3k** [comment]
I'd suggest we would target `basename` and `normalize` instead of `resolve` and `relative` for the remaining items as they are something exposed as `std/url` APIs.

We can revisit `resolve` and `relative` as they are requested

**Comment by iuioiua** [comment]
SGTM

**Comment by kt3k** [comment]
done
