### ISSUE TITLE
Unable to publish to jsr with CLI canary because of LICENSE file issue

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5555]
https://github.com/denoland/std/actions/runs/10110044499/job/27959158000

**Comment by iuioiua** [comment]
Is this still an issue? We do have a license file (see [here](https://github.com/denoland/std/blob/main/LICENSE)), but it's path doesn't match `/.LICENSE` (as indicated by the CI failure). Or is this path relative to `/async`?

**Comment by kt3k** [comment]
The issue was addressed in https://github.com/denoland/deno/pull/24747

The publish workflow now runs with canary since https://github.com/denoland/std/pull/5623
