### ISSUE TITLE
fs: `walk` on Windows does not return an absolute path

### ISSUE THREAD

**Issue by ryuapp** [denoland/std#5557]
**Describe the bug**

walk function should return absolute paths, but it on Windows does not return that.

**Steps to Reproduce**

```sh
# Dirctory
C:.
    deno.json
    deno.lock
    main.ts
```

```ts
// main.ts
import { walk } from "@std/fs/walk";
console.log(await Array.fromAsync(walk(".")))
```

```ts
// Result
[
  {
    path: ".",
    name: ".",
    isFile: false,
    isDirectory: true,
    isSymlink: false
  },
  {
    path: "deno.json",
    name: "deno.json",
    isFile: true,
    isDirectory: false,
    isSymlink: false
  },
  {
    path: "deno.lock",
    name: "deno.lock",
    isFile: true,
    isDirectory: false,
    isSymlink: false
  },
  {
    path: "main.ts",
    name: "main.ts",
    isFile: true,
    isDirectory: false,
    isSymlink: false
  }
]
```

**Expected behavior**

Return absolute paths.

**Environment**

- OS: Win10
- deno version: 1.45.3
- std version: `@std/fs@1.0.0`

**Comment by jsejcksn** [comment]
It is by design that `walk` returns paths relative to the root dir (first parameter). For context, see:

- https://github.com/denoland/std/issues/3456

If you'd like absolute paths for all entries, you can write a simple abstraction that uses [`Deno.realPath`](https://docs.deno.com/api/deno/~/Deno.realPath)/[`Deno.realPathSync`](https://docs.deno.com/api/deno/~/Deno.realPathSync) like this:

```ts
// main.ts

import { walk } from "@std/fs/walk";

const walkAbsolute: typeof walk = async function* (...args) {
  for await (const entry of walk(...args)) {
    entry.path = await Deno.realPath(entry.path);
    yield entry;
  }
};

console.log(await Array.fromAsync(walkAbsolute(".")));
```

**Comment by ryuapp** [comment]
@jsejcksn 
Thank you. It works well.
The reason I mistook this for a bug was because the JSDocs had examples of it returning an absolute path.

**Comment by jsejcksn** [comment]
> The reason I mistook this for a bug was because the JSDocs had examples of it returning an absolute path.

@ryuapp That's actually a good observation. The example data in the JSDoc for [`walk`](https://github.com/denoland/std/blob/release-2024.07.26/fs/walk.ts#L96-L450) and [`walkSync`](https://github.com/denoland/std/blob/release-2024.07.26/fs/walk.ts#L519-L872) should be modified. Are you interested in creating a PR to update it?

/cc @iuioiua

**Comment by ryuapp** [comment]
@jsejcksn 
Yes. I created the PR(#5559) to fix the examples.
I've modified them to reflect actual behavior.
