### ISSUE TITLE
csv: `fieldsPerRecord: -1` doesn't seem working

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5616]
The description says the below, but it seems to error on short number of fields even when it's set to a negative number.

> If negative, no check is made and records may have a variable number of fields.

**Comment by magurotuna** [comment]
I did a quick fix in https://github.com/denoland/std/pull/5605/commits/cd43e7836c365a4723ea50be0dd489e00e744d32

**Comment by magurotuna** [comment]
No this isn't #5606 but #5605

**Comment by kt3k** [comment]
Ah, ok. thanks!
