### ISSUE TITLE
[SUGGESTION] Duration module

### ISSUE THREAD

**Issue by rojvv** [denoland/std#5695]
## What

A module that makes casual duration conversion easier. It should be based on milliseconds.

## Use Cases

```ts
setTimeout(foo, 3 * SECOND);
const expiryDate = new Date(Date.now() + 3 * DAY);
```

**Comment by timreichen** [comment]
https://github.com/denoland/std/blob/main/datetime/constants.ts

**Comment by iuioiua** [comment]
[`@std/datetime/constants`](https://jsr.io/@std/datetime@0.224.5/doc/constants/~) and `@std/datetime` export these constants.

**Comment by rojvv** [comment]
@iuioiua Maybe you want to showcase them in this page https://jsr.io/@std/datetime

I visited there before creating the issue, didn’t know they were a thing.

**Comment by jd1378** [comment]
Maybe include the parse method from https://github.com/lukeed/ms/blob/master/src/index.js ?
it would allow something like this:
```
parse('2 days');   //=> 172800000
parse('1d');       //=> 86400000
```
