### ISSUE TITLE
ci: The `workspace publish` job seems to be failed on 2024.08.16

### ISSUE THREAD

**Issue by uki00a** [denoland/std#5709]
**Describe the bug**

[The `workspace publish` job seems to be failed on 2024/08/16](https://github.com/denoland/std/actions/runs/10415799497/job/28846895802) with the following error:

```
error: Following packages don't exist, follow the links and create them:
 - https://jsr.io/new?scope=std&package=cache&from=cli
Error: Process completed with exit code 1.
```

It seems to be caused by `@std/cache` not being created in JSR :eyes:

**Environment**

- OS: ubuntu-latest
- deno version: canary
- std version: [release-2024.08.16](https://github.com/denoland/std/releases/tag/release-2024.08.16)

**Comment by kt3k** [comment]
Thanks for catching this @uki00a !

Fixed in https://github.com/denoland/std/actions/runs/10440240479/job/28909900942
