### ISSUE TITLE
Proposal: change @std/archive to @std/tar

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/std#5733]
As it stands, @std/archive only contains one type of archive format, Tar. This proposal suggests that it should be renamed to its own @std module for the following reasons:
1. The std currently supports many file formats and all of them, with the exception of Tar, have their own module. They are named after said file format instead of by category of format. It makes no sense for Tar to be treated differently than these other file formats. 
    - @std/csv 
    - @std/dotenv 
    - @std/ini
    - @std/json 
    - @std/jsonc 
    - @std/msgpack 
    - @std/toml 
    - @std/yaml 
1. While there are many archive formats, many of them also double as file compression formats, and some file formats only offer compression. Assuming both @std/archive and @std/compress existed, how would a file format that supported both be categorised?

**Comment by iuioiua** [comment]
These are fair points. I'm open to having #4548 be implemented in a new `@std/tar` package. Though, let's wait to hear other's thoughts.

**Comment by iuioiua** [comment]
WDYT, @kt3k?
