### ISSUE TITLE
`yaml` bool type inconsistent boolean instance evaluation

### ISSUE THREAD

**Issue by timreichen** [denoland/std#5857]
**Describe the bug**
In `yaml/_types/bool.ts`, booleans are evaluated as
```ts
typeof value === "boolean" || value instanceof Boolean
```

This means `Boolean` instances are handled as booleans in yaml but the representation is evaluated as
```ts
represent: {
    lowercase(object: boolean): string {
      return object ? "true" : "false";
    },
    uppercase(object: boolean): string {
      return object ? "TRUE" : "FALSE";
    },
    camelcase(object: boolean): string {
      return object ? "True" : "False";
    },
}
```
This will always stringify `Boolean` instances to `"true"`, which  is probably not the intended behavior.

**Steps to Reproduce**
```ts
import { stringify } from "@std/yaml";
import { assertEquals } from "@std/assert";
assertEquals(stringify(new Boolean(false)), "true\n");
```

**Expected behavior**
`new Boolean(false)` should evaluate to `"false"` **OR**  `Boolean` instances should not be special treated and `value instanceof Boolean`  removed so they are handled as objects.

I am leaning torwards the removal. WDYT?

**Comment by iuioiua** [comment]
Yeah, it seems the predicate should just be `value === true || value === false`. I don't see why `Boolean` instances should be treated in any special way. I'm not aware of any such treatment elsewhere in the codebase.

**Comment by timreichen** [comment]
I'll open a PR. Would that be breaking or fix?
