### ISSUE TITLE
[Suggestion] Create searchable docs

### ISSUE THREAD

**Issue by jd1378** [denoland/std#5864]
**Is your feature request related to a problem? Please describe.**

Having a standard library for js sounds great, but Currently, It's not obvious in which part of std a method or utility might be. having a searchable document helps me and many others find the thing we need from std much faster.

**Describe the solution you'd like**

a client side PWA hosted on GitHub pages would suffice in my opinion. 

**Describe alternatives you've considered**

without a search, looking at https://jsr.io/@std is time consuming, and one might miss the thing they need because the library is big

**Comment by iuioiua** [comment]
The solution here is to simply improve search on JSR, and there are already [ongoing efforts](https://github.com/jsr-io/jsr/issues?q=is%3Aissue+is%3Aopen+search) to do so. If you'd like to help, I suggest helping out with those efforts. Either way, thank you for the suggestion.
