### ISSUE TITLE
Unstable APIs in stable packages should be more clearly marked as unstable

### ISSUE THREAD

**Issue by kt3k** [denoland/std#5920]
Currently we add the note `@experimental **UNSTABLE**: New API, yet to be vetted.` to the docs of unstable APIs. However there are feedbacks that this note is not enough for making the users aware of the unstableness of those APIs, and there are too high chance that users unintentionally start using them.

We currently consider moving unstable APIs under `unstable-` prefixed export paths. For example, (unstable) `route` API in `@std/http` becomes:

```diff
-import { route } from "@std/http/route";
+import { route } from "@std/http/unstable-route";
```

---

- [x] `std/assert`
  - `assertNever` function
- [x] `std/cli` #5946
  - `Spinner` class
  - `SpinnerOptions` type
  - `Color` type (part of `SpinnerOptions`)
- [x] `std/data-structures`
  - `BidirectionalMap` class
- [x] `std/encoding`
  - `Base32EncoderStream` class
  - `Base32DecoderStream` class
  - `Base32HexEncoderStream` class
  - `Base32HexDecoderStream` class
  - `Base64EncoderStream` class
  - `Base64DecoderStream` class
  - `Base64UrlEncoderStream` class
  - `Base64UrlDecoderStream` class
  - `HexEncoderStream` class
  - `HexDecoderStream` class
  - `encodeBase32Hex` function
  - `decodeBase32Hex` function
- [x] `std/front-matter/yaml` #5968 
  - `extract` function (the overload with option)
- [x] `std/html`
  - `isValidCustomElementName` function
- [x] `std/http` #5938
  - `HEADER` value
  - `Header` type
  - `METHOD` value
  - `Method` type
  - `Handler` type
  - `Route` type
  - `route` function #5939 
  - `signCookie` function
  - `verifySignedCookie` function
  - `parseSignedCookie` function
- [x] `std/net`
  - `getNetowrkAddress` function
- [x] `std/path`
  - `basename` function (URL overload) #5957
  - `dirname` function (URL overload) #5954
  - `extname` function (URL overload) #5962
  - `join` function (URL overload) #5964
  - `normalize` function (URL overload) #5967
- [x] `std/path/posix`
  - `basename` function (URL overload) #5957
  - `dirname` function (URL overload) #5954
  - `extname` function (URL overload) #5962
  - `join` function (URL overload) #5964
  - `normalize` function (URL overload) #5967
- [x] `std/path/windows`
  - `basename` function (URL overload) #5957
  - `dirname` function (URL overload) #5954
  - `extname` function (URL overload) #5962
  - `join` function (URL overload) #5964
  - `normalize` function (URL overload) #5967
- [x] `std/streams`
  - `toLines` function
  - `FixedChunkStream` class
- [x] `std/text`
  - `toConstantCase` function
  - `slugify` function
- [x] `std/uuid` #5937
  - `v7` namespace
- [x] `std/uuid/v7` #5937
  - `generate` function
  - `validate` function
  - `extractTimestamp` function

**Comment by BlackAsLight** [comment]
With the current note, are you trying to communicate that the public API is unstable in the sense that it might change drastically and in breaking ways or that it is free of malicious intent? 

When I hear the word unstable, I get the impression that it might change in breaking ways, but the latter part of the note "yet to be vetted" sounds like that's not the message trying to be communicated here.

**Comment by kt3k** [comment]
@BlackAsLight 
> With the current note, are you trying to communicate that the public API is unstable in the sense that it might change drastically and in breaking ways or that it is free of malicious intent?

It means it can be changed in breaking ways in the future. The phrase is traditionally used in CLI's API docs. Maybe it can be worded in a better way

@timreichen 
> How about logging a warning?

That might be another option, but there's also an opinion from the core team that it should be visible in sample code. (Warnings are only visible at runtime)

**Comment by iuioiua** [comment]
> How about logging a warning?

I'd rather not. We did this for deprecated APIs in preparation for Deno 2 and quickly reverted it, even with environment variables that disabled it. It seemed to cause more annoyance than provide help.

**Comment by kt3k** [comment]
These 51 APIs are targets of this change.

https://gist.github.com/kt3k/f6754c2fa5b90cc6ef7c03396aa90b37

**Comment by kt3k** [comment]
Added the task list in the first comment.
