### ISSUE TITLE
`pick` shouldn't pick missing keys

### ISSUE THREAD

**Issue by yuhr** [denoland/std#5922]
https://github.com/denoland/std/blob/582a9f2af1d33fc5adb4cc2301f77df444bb4ce7/collections/pick.ts#L18-L23

This way, keys not present in the original object will be added with the value being `undefined` in the returned object. Is this intended behavior?

**Comment by iuioiua** [comment]
`pick()` was modelled after Lodash's [`pick()`](https://lodash.com/docs/#pick), which ignores keys that are absent from `obj`. So this seems to be unexpected behavior. WDYT, @lambdalisue?

**Comment by kt3k** [comment]
Is there practical downside of this behavior? In other words, is there practically confusing case with this behavior?

**Comment by iuioiua** [comment]
If a user accidentally defines a non-existent key, they might be surprised to see said key in the resulting object. However, that should be relatively trivial to troubleshoot. I'm mostly impartial to us changing this behavior.

**Comment by yuhr** [comment]
> is there practically confusing case

I was trying to use `deno.json` as an import map:

```typescript
import { parse } from "https://esm.sh/v135/@import-maps/resolve@2.0.0"

const url = new URL(import.meta.resolve("./deno.json"))
const importMap = parse(JSON.parse(await Deno.readTextFile(url)), url)

console.log(importMap)
```

But this emits warnings about unnecessary properties:

```typescript
Invalid top-level key "lock". Only "imports" and "scopes" can be present.
Invalid top-level key "compilerOptions". Only "imports" and "scopes" can be present.
{ imports: {}, scopes: {} }
```

So I was supposed to pick only `imports` and `scopes` properties from `deno.json`:

```typescript
import { parse } from "https://esm.sh/v135/@import-maps/resolve@2.0.0"
import { pick } from "https://raw.githubusercontent.com/denoland/std/release-2024.09.04/collections/pick.ts"

const url = new URL(import.meta.resolve("./deno.json"))
const importMap = parse(pick(JSON.parse(await Deno.readTextFile(url)), ["imports", "scopes"]), url)

console.log(importMap)
```

But this emits an error:

```
error: Uncaught (in promise) TypeError: Import map's scopes value must be an object.
```

This is because the `deno.json` doesn't have `scopes` property originally. `pick` adds it as `undefined`, thus I have to filter out beforehand.

It's counter-intuitive that a function named `pick` generates new properties.

**Comment by yuhr** [comment]
I think the behavior of Lodash doesn't matter here, because the standard library is not Lodash anymore.

Basically, “transformer” functions like this should preserve the semantics of the original value as much as possible. The absence of property sometimes means different thing than the presence with `undefined`.

**Comment by lambdalisue** [comment]
@iuioiua Yes. It is unexpected.

I think we can define it like below (it's not as performant as current implementation) 

```ts
export function pick<T extends object, K extends keyof T>( 
  obj: Readonly<T>, 
  keys: readonly K[], 
): Pick<T, K> { 
  const base = new Set([
     ...Object.keys(obj),
     ...Object.getOwnPropertySymbols(obj),
  ]);
  const ks = base.intersection(new Set(keys));
  return Object.fromEntries([...ks].map((k) => [k, obj[k]])) as Pick<T, K>; 
}
```

**Comment by yuhr** [comment]
@lambdalisue With that code, the function ignores the prototype and the property descriptors of the original object.

I think the code should be:

```typescript
export function pick<T extends object, K extends keyof T>( 
  obj: Readonly<T>, 
  keys: readonly K[], 
): Pick<T, K> { 
	const result = Object.create(Object.getPrototypeOf(obj))
  const descriptors = Object.getOwnPropertyDescriptors(obj)
	for (const key of keys) {
		if (Object.hasOwn(descriptors, key)) {
			Object.defineProperty(result, key, descriptors[key])
		}
	}
	return result
}
```

**Comment by yuhr** [comment]
I'm going to file a new issue about preserving prototypes and property descriptors, covering `pick`, `omit`, and the like.
