### ISSUE TITLE
`@std/fs` `exists[Sync]` Does Not Require `--allow-sys` Any More?

### ISSUE THREAD

**Issue by catuhana** [denoland/std#5977]
**Describe the bug**
Not using `--allow-sys` does not change anything for those functions, but they're mentioned in the documentation that it is required.

**Steps to Reproduce**
*None*

**Expected behavior**
*Not relevant*

**Environment**
- std version: `@std/fs/1.0.3`

**Comment by iuioiua** [comment]
I've submitted #5983 that clarifies when/why `--allow-sys` is needed.
