### ISSUE TITLE
Return type of `http/getCookies` is `Record<string, string>` instead of `Record<string, string | undefined>`

### ISSUE THREAD

**Issue by canac** [denoland/std#5979]
**Is your feature request related to a problem? Please describe.**

Because the return type of `getCookies` in the `http` package is `Record<string, string>`, any cookie you try to access has the type `string`, even if it is not actually present.

**Describe the solution you'd like**

Change the return type of `getCookies` to `Record<string, string | undefined>`. (I understand that this would be a breaking change, and may not be feasible in the near-future).

**Describe alternatives you've considered**

I can obviously validate the cookie values in my code. But it would be nice if the type were `string | undefined` so that TypeScript would complain if I tried to use it as a string without first checking that it is undefined.

**Comment by iuioiua** [comment]
Good catch. I'd happily take a look at a PR that implements this fix.

**Comment by canac** [comment]
> I'd happily take a look at a PR that implements this fix.

@iuioiua Done!

**Comment by kt3k** [comment]
I'm not in favor of this change. This is a disruptive breaking change to a stable module. We can't do this change in the near future.

> Because the return type of getCookies in the http package is Record<string, string>, any cookie you try to access has the type string, even if it is not actually present.

If you like to get property access to be typed as `string | undefined`, you can opt in to stricter type settings by enabling `noUncheckedIndexedAccess` option in `compilerOptions`:

```json
{
  "compilerOptions": {
    "noUncheckedIndexedAccess": true
  }
}
```

By this enabled, any property of `Record<string, string>` is typed `string | undefined`.

**Comment by canac** [comment]
@kt3k I completely understand not wanting to make a breaking change so soon after this module was stabilized.

Also, thanks for the tip about `noUncheckedIndexedAccess`. I knew about that flag for arrays but didn't know it works on objects too. That is exactly what I'm looking for.

**Comment by iuioiua** [comment]
Ah, I forgot about `noUncheckedIndexedAccess`. I'll mark this issue as closed (answered by Yoshiya), and close the corresponding PR.
