### ISSUE TITLE
experiment: BYO test coverage explorer

### ISSUE THREAD

**Issue by iuioiua** [denoland/std#5982]
We want to experiment with having a "BYO test coverage explorer" by serving `deno coverage --html` output instead of using Codecov. To start the experiment, we need to create a Deno Deploy project. Initial experiments show this is what's required (must be done by admin account):

- Project name: `std-test-cov`
- Repo: `denoland/deno`
- Install step: `deno task test`
- Build step: `deno coverage --html`
- Root directory: `coverage/html`
- Production branch: `main`
- Entrypoint: `https://deno.land/std/http/file_server.ts`

Pilot [here](https://ashergomez-std-65.deno.dev/)

**Comment by kt3k** [comment]
Do we commit the coverage report files in the repository? I'd prefer to avoid it as it feels like the noise to the commit history.

**Comment by iuioiua** [comment]
Is there a way to specify where `deno coverage --html` output is written? If not, we should add one.

Otherwise, to remove everything from `/coverage` except `/coverage/html`, we'd have to use a complicated command like:
```
find /coverage -mindepth 1 -maxdepth 1 ! -name 'html' -exec rm -rf {} +
```

**Comment by kt3k** [comment]
> Is there a way to specify where deno coverage --html output is written? If not, we should add one.

There seems none

> Otherwise, to remove everything from `/coverage` except `/coverage/html`, we'd have to use a complicated command like:
> 
> ```
> find /coverage -mindepth 1 -maxdepth 1 ! -name 'html' -exec rm -rf {} +
> ```

All raw coverage data are in the form of `<uuid>.json`. This can be simplified to

```
rm coverage/*.json
```

**Comment by iuioiua** [comment]
> All raw coverage data are in the form of `<uuid>.json`. This can be simplified to
> 
> ```
> rm coverage/*.json
> ```

I get the following on my machine:
```
zsh: argument list too long: rm
```

**Comment by kt3k** [comment]
Then maybe use:

```
find coverage -name "*.json" -delete
```

**Comment by kt3k** [comment]
BTW I'm now not in favor of this move if we try to commit the coverage report to the repository. They will be huge noise. It duplicates the entire std source code embedded in html

**Comment by iuioiua** [comment]
This won't commit the coverage report to the repo.

**Comment by iuioiua** [comment]
It seems that files outside of `coverage/html` aren't uploaded to Deploy. The assets uploaded are roughly equal to the amount of files contained within `coverage/html`. I think this is thanks to how Deploy handles the root directory.

**Comment by iuioiua** [comment]
In other words, deleting the JSON files may not be needed.

**Comment by iuioiua** [comment]
Ping @kt3k

**Comment by BlackAsLight** [comment]
To keep the commit history clean, why not have a separate branch where a GitHub action auto updates it?

**Comment by iuioiua** [comment]
Maybe deploy daily?

**Comment by BlackAsLight** [comment]
An alternative option would be to use GitHub Pages and publish with GitHub Actions. Wouldn't even need to commit to the repo and it could update with every push to the main branch
