### ISSUE TITLE
dotenv: Warn about using DENO_ prefixed variables

### ISSUE THREAD

**Issue by ycmjason** [denoland/std#6127]
I recently encountered an issue while trying to use the `DENO_KV_PATH` environment variable that will be used in `openKv` on Deno Deploy.

The problem is that it consistently fails, and after checking the logs, it appears that Deno Deploy doesn't allow environment variables prefixed with `DENO_`. The error message I received was:

```
Env vars cannot begin with DENO_
```

Upon renaming the env variable to `CUSTOM_DENO_KV_PATH` it starts working again.

I haven’t seen this limitation documented anywhere for Deno Deploy, but I think it’s something worth highlighting. It would also be helpful if dotenv could issue a warning when this happens.

Just thought it might be useful to bring this to your attention.

**Comment by iuioiua** [comment]
This is not an issue for `std`.

**Comment by ycmjason** [comment]
> This is not an issue for `std`.

That's fair and make sense. A warning from Deno Deploy should be sufficient. Closing this issue.
