### ISSUE TITLE
fs.ensure_symlink throwing error in browser

### ISSUE THREAD

**Issue by QuixThe2nd** [denoland/std#6132]
**Describe the bug**

On [line 8 of ensure_symlink.ts](https://github.com/denoland/std/blob/a541fb468ccf67787cf28e3fd954ebcc2035fc46/fs/ensure_symlink.ts#L8) on-import the script checks if the user is on windows (`const isWindows = Deno.build.os === "windows";`). Deno however is undefined in browser throwing a fatal error.
![image](https://github.com/user-attachments/assets/d3856265-1c08-4ffc-9877-6b579d8d2850)

**Steps to Reproduce**

1. Build project with:
```
import * as esbuild from "npm:esbuild";
await esbuild.build({ plugins: [...denoPlugins()], entryPoints: ["./src/in.ts"], outfile: "./dist/out.js", bundle: true, format: "esm", platform: "browser" });
```
2. Import in web:
```
    <script type="module" src="hydrafiles-web.esm.js"></script>
    <script type="module">
    import Hydrafiles from './hydrafiles-web.esm.js';
    </script>
```
3. Error in browser logs

**Expected behavior**

A check should be done before `Deno.build.os === "windows"` to first check if user is in Deno environment. For example:
```
const isWindows = window !== undefined && Deno.build.os === "windows";
```

**Environment**

- OS: N/A
- deno version: 2.0
- std version: 0.221.0

**Comment by QuixThe2nd** [comment]
I would have sent a pull request, but I am new to Deno. I'm not confident the error isn't my fault.

**Comment by kt3k** [comment]
What is the expected behavior of `ensureSymlink` in browser?

**Comment by QuixThe2nd** [comment]
> What is the expected behavior of `ensureSymlink` in browser?

If it's imported in a script that runs in both browser and Deno, it throws an error on import. It should instead throw the error when `ensureSymlink` is called.

**Comment by kt3k** [comment]
> It should instead throw the error when ensureSymlink is called.

Ah, ok. That makes sense to me.
