### ISSUE TITLE
@std/tar append entry to current tar

### ISSUE THREAD

**Issue by sant123** [denoland/std#6136]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I do not find a way to append an entry to an existing tar file. It would be nice to specify in the TarStream constructor an append option: 

`someStream.pipeThrough(TarStream({ append: true }))`

**Describe alternatives you've considered**

Create the tar again with the new files, however the tar command in [Unix](https://www.math.utah.edu/docs/info/tar_4.html#:~:text=tar%20can%20be%20used%20to,'%20(%20%60%2DA'%20).) offers a way to append an entry. 

Thanks 🙏🏼

**Comment by BlackAsLight** [comment]
Appending to a file requires knowing where in the tarball the end marker is located.
- If the tarball was originally made with `@std/tar` then that's guaranteed to be 1024 bytes from the end of the file, but;
- Tarballs from other places (Like from GitHub releases) may have additional empty bytes at the end for whatever reason, meaning one would need to jump through the file reading every header along the way to find that end marker.
- For this type of jumping to be possible the tar file can't be compressed as there is no way to know how far to jump to find the next header.
- Meaning compressed tar files need to go through a slow decompression and then recompression simply to append a file.

There are other things to consider as well.
- Adding this type of feature to `@std/tar` would remove it's ability to work on all runtimes, and only a specific, non-browser runtime.
- I know how to overwrite files and append new content to existing files in Deno, but I don't know how to delete only a specific part of a file before appending more content in Deno.

In your alternatives you've considered, you tried creating the tar again with the new files. This below code should do that by first untaring the tarball to retar it immediately and then append the new file afterwards. I would maybe suggest looking at an alternative approach to whatever you're trying to accomplish with the tarballs.
```ts
import { TarStream, UntarStream } from "@std/tar";

const tar = new TarStream();
const writer = tar.writable.getWriter();

// Promise resolves when creating the new tarball is complete
const promise = tar
  .readable
  .pipeTo((await Deno.create("tmp.tar")).writable);

// Untar the current tarball
for await (
  const tarEntry of (await Deno.open("archive.tar"))
    .readable
    .pipeThrough(new UntarStream())
) {
  // Retar the untared files.
  await writer.write(
    tarEntry.readable
      ? {
        type: "file",
        path: tarEntry.path,
        size: tarEntry.header.size,
        readable: tarEntry.readable,
        options: tarEntry.header,
      }
      : {
        type: "directory",
        path: tarEntry.path,
        options: tarEntry.header,
      },
  );
}

// Append new file here
await writer.write({
  type: "file",
  path: "movie.mp4",
  size: (await Deno.stat("movie.mp4")).size,
  readable: (await Deno.open("movie.mp4")).readable,
});

await writer.close();
await promise;

await Deno.remove("archive.tar");
await Deno.rename("tmp.tar", "archive.tar");

```

**Comment by sant123** [comment]
@BlackAsLight thank you so much for taking the time in this code 🙏🏼
