### ISSUE TITLE
Error "Received function must be a mock or spy function" when passing a stub to expect(...).toHaveBeenCalled()

### ISSUE THREAD

**Issue by mspiess** [denoland/std#6140]
**Describe the bug**
A stub is not accepted as such, because the `expect` matchers [check for a symbol](https://github.com/denoland/std/blob/3f0ef9f502a5368b029537a74cf262ac6f7f11d1/expect/_mock_util.ts#L4) which the `stub` function [does not seem to set](https://github.com/denoland/std/blob/3f0ef9f502a5368b029537a74cf262ac6f7f11d1/testing/mock.ts#L1087).

**Steps to Reproduce**

1. Create a file `main_test.ts` with the contents 
    ```typescript
    import {stub} from 'jsr:@std/testing/mock';
    import {expect} from "jsr:@std/expect";
    
    Deno.test(function someTest() {
        const fetchStub = stub(globalThis, 'fetch', () => Promise.resolve(new Response(JSON.stringify([]))));
    
        await fetch('');
    
        expect(fetchStub).toHaveBeenCalled();
    });
    ```

2. Run the command `deno test`
3. See error
    ```
    error: Error: Received function must be a mock or spy function
    throw new Error("Received function must be a mock or spy function");
          ^
    at getMockCalls (https://jsr.io/@std/expect/1.0.5/_mock_util.ts:18:11)
    at toHaveBeenCalledWith (https://jsr.io/@std/expect/1.0.5/_matchers.ts:540:17)
    at applyMatcher (https://jsr.io/@std/expect/1.0.5/expect.ts:218:13)
    at Proxy.<anonymous> (https://jsr.io/@std/expect/1.0.5/expect.ts:228:13)
    ```

**Expected behavior**

The test should pass.

**Environment**

- OS: alpine running on docker engine in Ubuntu WSL on Windows 10
- deno version: 2.0.2
- std version:
  - [@std](https://jsr.io/@std)/[expect](https://jsr.io/@std/expect)@1.0.5
  - [@std](https://jsr.io/@std)/[testing](https://jsr.io/@std/testing)@1.0.3

**Comment by andrewthauer** [comment]
The current stub/spy's are not directly compatible with `expect`. You can however workaround this by using `fn` as an intermediate for the spy tracking. For example:

```ts
import {stub} from 'jsr:@std/testing/mock';
import {expect, fn} from "jsr:@std/expect";

Deno.test(function someTest() {
    const mockFetch = fn(() => Promise.resolve(new Response(JSON.stringify([]));
    const fetchStub = stub(globalThis, 'fetch', mockFetch);

    await fetch('');

    expect(mockFetch).toHaveBeenCalled();
});
``` 

That said `fn` is not typed to `Function` for input/output so it requires casting. I've been meaning to file a GH issue about `fn` typing as well.

**Comment by kt3k** [comment]
`@std/testing/mock` and `@std/expect` are not supposed to work together.

If you use `stub` from `@std/testing/mock`, please use assertions in the same module (such as `assertSpyCall`)

If you prefer to use mock assertions from `@std/expect`, then use `fn` in `@std/expect` for stubbing/mocking/spying as @andrewthauer suggests
