### ISSUE TITLE
[@std/dotenv] can't handle multi line variable 

### ISSUE THREAD

**Issue by ryanhex53** [denoland/std#6170]
**Describe the bug**

the `@std/dotenv` library can't handle multi line variable correctly, it only return the first line of the string.

**Steps to Reproduce**

.env
```env
KEY="one line string
second line string"
```

main.ts
```ts
import { load } from "@std/dotenv";
await load({ export: true });
console.log(Deno.env.get("KEY"));
```
`deno run -A main.ts` get output `one line string`

But if don't use `@std/dotenv`, only `deno run -A --env-file main.ts` 
main.ts
```ts
console.log(Deno.env.get("KEY"));
```
will get correct output `one line string\nsecond line string`

**Expected behavior**

get multiline output `one line string\nsecond line string` while use `@std/dotenv`

**Environment**

- OS: Window 10
- deno version: 2.0.4
- std/dotenv version: 0.225.2

**Comment by IgorM867** [comment]
It seems like a problem with line breaks on Windows. Windows uses `\r\n` for line breaks, while Unix, Linux, and macOS use `\n`. In VS Code, you can change the line break style of the file in the bottom-right corner."

**Comment by ryanhex53** [comment]
Correct, it works without issues after changing the End of Line Sequence to LF.
