### ISSUE TITLE
@std/testing/mock: Can't stub a function that has multiple signatures

### ISSUE THREAD

**Issue by zing-rsa** [denoland/std#6172]
**Describe the bug**
I am unable to figure out how I would stub a function which has multiple signatures. The current syntax: `const my_stub = stub(test, "testFunction")` doesn't seem to offer the ability to target a specific signature to stub. 

**Steps to Reproduce**
See example: 
```ts
// my class with multiple signatures for the testFn function
class Test {
    testFn(query: number): void;
    testFn(query: string): void;
    testFn(args: string | number): void {
        console.log(args);
    }
}

// my test
Deno.test("test", () => {
    const test = new Test();

    const myStub = stub(test, "testFn")

    test.testFn(123);

    assertSpyCall(myStub, 0, {
        args: [ 123 ] 
        //      ^^^ deno-ts(2322): Type 'number' is not assignable to type 'string'
    })
});
```

**Expected behavior**
I should be able to stub the function and verify that argument types which are consistent with either of the signatures are passed in.

**Environment**

- OS: Ubuntu 22.04.4 LTS
- deno version: deno 1.46.3
- std version: @std/testing 1.0.4

**Comment by IgorM867** [comment]
You can work around this by explicitly casting the stub to a type that matches multiple overloads, like this:
```ts
Deno.test("test", () => {
  const test = new Test();

  const myStub = stub(test, "testFn") as Stub<Test, [query: string | number], void>;

  test.testFn(123);

  assertSpyCall(myStub, 0, {
    args: [123],
  });
});
```

**Comment by zing-rsa** [comment]
ohh these are great man thank you 🙏🏼
