### ISSUE TITLE
[@std/testing/snapshot]: Could not generate snapshot file automatically

### ISSUE THREAD

**Issue by eryue0220** [denoland/std#6178]
**Describe the bug**

According to the [snapshot testing](https://jsr.io/@std/testing/doc/snapshot) doc, the `.snap` file should generate automatically, if the test case is created at the first time. But actually it will throw an error:

```shell
AssertionError: Missing snapshot: isSnapshotMatch 1
      throw new AssertionError(
            ^
    at assertSnapshot (https://jsr.io/@std/testing/1.0.4/snapshot.ts:606:13)
    at async file:///Users/xxx/deno/deno-snapshot-test/tests/example_test.ts:8:3
```

**Steps to Reproduce**
Execute the followint command in the terminal:
```shell
1. git clone https://github.com/eryue0220/deno-snapshot-test
2. cd deno-snapshot-test
3. deno test
```

**Expected behavior**

1. Should not throw an error.
2. Generate a `.snap` file if there is no corresponding `.snap` file.

**Environment**

- OS: [MacOS 15.1]
- deno version: 1.45
- std version: jsr:@std/testing@^1.0.4

**Comment by IgorM867** [comment]
I can't find any information in the documentation indicating that the .snap file should be generated automatically.

![image](https://github.com/user-attachments/assets/45d6c6e3-9e7c-4f73-8677-adf8db7fbe9a)

From the docs, it looks like you need to run `deno task` with the `--update` flag when adding a new snapshot.

**Comment by eryue0220** [comment]
> I can't find any information in the documentation indicating that the .snap file should be generated automatically.
> 
> ![image](https://private-user-images.githubusercontent.com/116740171/384255444-45d6c6e3-9e7c-4f73-8677-adf8db7fbe9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDQ0MDYsIm5iZiI6MTczMTMwNDEwNiwicGF0aCI6Ii8xMTY3NDAxNzEvMzg0MjU1NDQ0LTQ1ZDZjNmUzLTllN2MtNGY3My04Njc3LWFkZjhkYjdmYmU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwNTQ4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDhiZDZjMmFlYmRlNjFlZGY4NjMyMDA0NzMxOTQyNTZmNjdmMjdkYTJmNTZkNjM5OWVkNTcwNTY0NDQxYjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YD_Sgzl8y97hhVjtpJ4IflCkIWhhzkUm_fbpfIVJpjw)
> 
> From the docs, it looks like you need to run `deno task` with the `--update` flag when adding a new snapshot.

Sorry for the mistake, what I mean is that when no snapshot file, the `.snap` file should generate automatically. But the picture you provide give me a great answer.
