### ISSUE TITLE
fs.ensureSymlink does not work!

### ISSUE THREAD

**Issue by amir-reza-bijandi** [denoland/std#6191]
**Describe the bug**
`ensureSymlink` method does not work! Well... Mostly...
I'm new to using Deno and it's std library and I was trying out @std/fs and that's when I encountered an error with my very basic code...

```typescript
await fs.ensureSymlink("./dir/test.txt", "./dir/test.link.txt");
```
Error:
```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2): lstat '/home/arb/Programming/Javascript/Practice/deno-hello-world/dir/dir/test.txt'
  const srcStatInfo = await Deno.lstat(targetRealPath);
                      ^
    at async Object.lstat (ext:deno_fs/30_fs.js:397:15)
    at async Module.ensureSymlink (https://jsr.io/@std/fs/1.0.5/ensure_symlink.ts:56:23)
    at async file:///home/arb/Programming/Javascript/Practice/deno-hello-world/main.ts:6:1
```

As you can see the target file exists and i'm trying to create the symlink inside the same directory as the target file:
![Screenshot From 2024-11-17 21-38-41](https://github.com/user-attachments/assets/366bc47e-d058-4c5b-9b5f-e342ad5316b6)

I tried removing the `./` from the paths, but it didn't work, and I got the same error again.
The funny part is that if the target file and the path for creating symlink are both at the root of the working directory, The method work! So this line of code works with no problem:

```typescript
await fs.ensureSymlink("test.txt", "test.link.txt");
```

One more thing that i tried that also did not work was this:
```typescript
await fs.ensureSymlink("test.txt", "new-dir/test.link.txt");
```

I even made the `new-dir` directory myself but i still got the same error.

**Steps to Reproduce**

I'm not doing anything special!
1. Create a new project using `deno init`
2. Change content of `main.ts` to this:
```typescript
import * as fs from "@std/fs";

await fs.ensureSymlink("./dir/test.txt", "./dir/test.link.txt");
``` 
3. Create a file with this path: `./dir/test.txt`

**Expected behavior**

Creating a new symlink?

**Environment**

- OS: Fedora 41
- deno version: 2.0.6 (Stable)
- std version: @std/fs 1.0.5

**Comment by kt3k** [comment]
It looks like the first argument needs to be a relative path from **link's path** to **target**. If I modified the main.ts like the below, it worked:

```js
import * as fs from "@std/fs";
await fs.ensureSymlink("./test.txt", "./dir/test.link.txt");
```

```shellsession
$ tree dir 
dir
├── test.link.txt -> ./test.txt
└── test.txt

1 directory, 2 files
```

I agree this is not clear from the documentation. I think we need to update the parameter document to make this clear.

**Comment by amir-reza-bijandi** [comment]
> I agree this is not clear from the documentation. I think we need to update the parameter document to make this clear.

I don't think it's a documentation issue. The reason for that is that it just doesn't make any sense. Just think about it, `Deno.symlink` and `fs.ensureLink` do not have this issue and do not need a relative relation between two paths, so why would `fs.ensureSymlink` behave this way?

Even after seeing your solution and testing it, it just doesn't click in my head... I get it... but it always takes a second to process what the hell is going on...

**Comment by kt3k** [comment]
I checked how `Deno.symlink` works, and it looks like working as the same way as `fs.ensureSymlink`:

When you have file in this way:
```
$ tree dir 
dir
└── file.txt
```

and you'd like to create a symlink `dir/link.txt` pointing `dir/file.txt`, then you need to call `Deno.symlink` like:

```ts
await Deno.symlink("file.txt", "dir/link.txt");
```

and the below doesn't work (the below script creates a broken symlink):

```ts
await Deno.symlink("dir/file.txt", "dir/link.txt");
```

---

I think this behavior comes from how `ln -s` command works. If you like to achieve the same as `ln -s`, you need to call:

```sh
ln -s file.txt dir/link.txt
```

and the below creates a broken link:

```sh
ln -s dir/file.txt dir/link.txt
```

**Comment by amir-reza-bijandi** [comment]
That makes sense! I think, as a beginner, what makes this even more confusing is that the end results of using `Deno.symlink` and `fs.ensureSymlink` are different! When using `Deno.symlink`, I get a broken link that I can investigate by checking its target. On the other hand, using `fs.ensureSymlink` gives me an uncaught error.

I think, in a perfect scenario, we should get the same result. But if that's not possible, there needs to be a more descriptive error message. The current error message simply states that something went wrong in the method's implementation.

```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2): lstat '/home/arb/Programming/Javascript/Practice/deno-hello-world/dir/dir/test.txt'
  const srcStatInfo = await Deno.lstat(targetRealPath);
                      ^
```

As an end-user of this method, I don't know why `Deno.lstat` is failing or how to prevent it. Even if the documentation is improved, and I'm making mistakes, there should be a way for me to understand what's happening without relying solely on the documentation.

**Comment by kt3k** [comment]
Then how about changing the error message to something like `Cannot ensure symlink as the target path does not exist: path/to/target_file`?

**Comment by amir-reza-bijandi** [comment]
It's a huge improvement! I'd still recommend improving the documentation for this method as well. 

**Thanks a lot for your awesome job!** 🫡
