### ISSUE TITLE
assertEquals doesn't correctly compare Blobs

### ISSUE THREAD

**Issue by EvanHahn** [denoland/std#6202]
**Describe the bug**

`assertEquals` doesn't consider value-equal `Blob`s to be equal.

**Steps to Reproduce**

Run the following code:

```javascript
import { assertEquals } from "jsr:@std/assert";
assertEquals(new Blob(["foo"]), new Blob(["foo"]));
```

**Expected behavior**

This should not throw an error. Instead, it throws `AssertionError: Values are not equal.`

**Environment**

- OS: macOS 15
- deno version: 2.1.0
- std version: 1.0.8

**Comment by IgorM867** [comment]
To compare `Blob` objects, `assertEquals`  needs to handle asynchronous operations. One approach could be transforming Blob objects into Uint8Array:
```ts
import { assertEquals } from "@std/assert";

const bytes1 = await new Blob(["foo"]).bytes();
const bytes2 = await new Blob(["foo"]).bytes();

assertEquals(bytes1, bytes2);
```
In Node.js, this also doesn’t work:
```ts
import assert from "node:assert/strict";

assert.deepStrictEqual(new Blob(["foo"]), new Blob(["foo"]));
```

@kt3k, what do you think about adding support for `Blob` in `assertEquals` and convert it to asynchronous function?

**Comment by kt3k** [comment]
@IgorM867 Thanks for looking into this. And I don't think we can fix this as `assertEquals` is a stable API and we can't make breaking change to it. (Changing `assertEquals` to async function has too large impact to the ecosystem)

I think the best thing we can do is adding note about it, maybe along with the above example.
