### ISSUE TITLE
`test` is not exactly an alias for `it`

### ISSUE THREAD

**Issue by dandv** [denoland/std#6220]
**Describe the bug**

https://jsr.io/@std/testing/doc/bdd/~/test states that `test` is an "Alias of [`it`](https://jsr.io/@std/testing/doc/bdd/~/it)". But `test` does not have the `only`, `ignore`, and `skip` methods from `it`. This makes it incompatible with Jest test suites, for example.

**Steps to Reproduce**

`test.only(..)` will produce

> Property only does not exist on type <T>(...args: ItArgs<T>) => void

**Comment by kt3k** [comment]
Good catch!
