### ISSUE TITLE
Add a function to create a pierced array

### ISSUE THREAD

**Issue by aminnairi** [denoland/std#6229]
**Is your feature request related to a problem? Please describe.**

It would be great to have a function that creates a pierced array in the `@std/collections` package.

**Describe the solution you'd like**

A function that takes an array, and returns an array of array, such as each value of the outermost array is the array taken as argument, without the value at each index.

```typescript
const array = [1, 2, 3];

const pierced = [
  [2, 3],
  [1, 3],
  [1, 2]
];
```

**Describe alternatives you've considered**

None.

**Comment by aminnairi** [comment]
Implementation

```typescript
import { expect } from "jsr:@std/expect";

function pierced<Item>(items: Item[]): Item[][] {
  return items.map((_, unwantedIndex) => {
    return items.filter((_, index) => unwantedIndex !== index);
  });
}

Deno.test("Should return a pierced array", () => {
  const result = pierced([1, 2, 3]);

  expect(result).toStrictEqual([[2, 3], [1, 3], [1, 2]]);
});

Deno.test("Should return an empty array when given an empty array", () => {
  const result = pierced([]);

  expect(result).toStrictEqual([]);
});
```

**Comment by andrewthauer** [comment]
Curious what the use cases are for this? I've also never heard of the term pierced array before. I couldn't find anything easily on the web, so curious where does this term come from?

**Comment by aminnairi** [comment]
Oh wong repo!

But FYI, it was because I'm creating an accounting app that helps accountant do bank reconciliations with partial/complete payments, and it is quite interesting to have combine with a permutation generation, I guess it can be interesting to have also in Deno but maybe later!
