### ISSUE TITLE
expect.arrayContaining + expect.objectContaining broken

### ISSUE THREAD

**Issue by dandv** [denoland/std#6243]
A common use case in testing is making sure an array contains an object with a given shape. [This blog post](https://medium.com/@andrei.pfeiffer/jest-matching-objects-in-array-50fe2f4d6b98) discusses it. The code from the blog post works with Jet but fails with `@std/expect`. Example (with additional test) below.

**Steps to Reproduce**

```ts
import { test } from '@std/testing/bdd';
import { expect } from '@std/expect';

const a = [
  { foo: 'bar' },
  { foo: 'baz' },
];

test('matchObject on array', () => {
  expect(a).toEqual(expect.arrayContaining([
    expect.objectContaining({ foo: 'bar' }),
  ]));
});

const state = [
  { type: "START", data: "foo" },
  { type: "START", data: "baz" },
  { type: "END", data: "foo" },
];

test("test from blog post", () => {
  expect(state).toEqual(
    // 1
    expect.arrayContaining([
      // 2
      expect.objectContaining({
        // 3
        type: "END", // 4
      }),
    ])
  );
});

```

**Expected behavior**

[CodeSanbox](https://codesandbox.io/p/sandbox/deno-std-expect-arraycontaining-objectcontaining-broken-vds8wf?workspaceId=ws_Ga64P2NM3YRhX6z7UXGAW1)

**Environment**

- deno version: 2.1.3
- @std/expect version: 1.0.9

**Comment by eryue0220** [comment]
Thank you for your feedback, I'll check this case later.
