### ISSUE TITLE
Can't assert that an async function taking parameters and awaiting, throws?

### ISSUE THREAD

**Issue by dandv** [denoland/std#6250]
I'm trying to use `assertThrows` or `assertRejects` to assert that an async function taking a parameter and awaiting a `fetch` call, throws. This is the function:

```ts
async function asyncFuncThatAwaitsAndThrows(format = 'json') {
  await fetch(`https://api.ipify.org?format=${format}`);
  throw new Error('This async function awaited and had to throw');
}
```

`assertRejects(asyncFuncThatAwaitsAndThrows)` correctly does not throw and the test passes. Because `asyncFuncThatAwaitsAndThrows` must take parameters, it needs to be called like this from `assertRejects`:

```ts
assertRejects(() => asyncFuncThatAwaitsAndThrows('text'));
```

But that leads to an error that leaks were detected:

> -  "fetchCancelHandle" was created during the test, but not cleaned up during the test. Close the resource before the end of the test.
> - An async operation to send a HTTP request was started in this test, but never completed. This is often caused by not awaiting the result of a `fetch` call.
  
However, `asyncFuncThatAwaitsAndThrows` did await the fetch.

Using `assertThrows` apparently makes the function NOT throw:

```ts
assertThrows(async () => await asyncFuncThatAwaitsAndThrows('text'));
```

> error: AssertionError: Expected function to throw.

**Steps to Reproduce**

```ts
import { assertRejects, assertThrows } from "@std/assert";

async function asyncFuncThatThrows(param?: string) {
  throw new Error(`This async function throws ${param}`);
}

async function asyncFuncThatAwaitsAndThrows(format = 'json') {
  await fetch(`https://api.ipify.org?format=${format}`);  // i.e. some async operation in a real use case
  throw new Error('This async function awaited and had to throw');
}

function funcThatThrows(param?: string) {
  throw new Error(`This function throws ${param}`);
}

Deno.test('this test should pass and not throw',  async () => {
  // await asyncFuncThatThrows();  // correctly throws, test fails
  assertRejects(asyncFuncThatThrows);  // correctly does NOT throw, test passes
  // assertRejects(asyncFuncThatThrows('bar'));  // incorrect syntax, must use arrow function to pass param
  assertRejects(() => asyncFuncThatThrows('bar'));  // correctly does NOT throw, test passes
  assertThrows(() => funcThatThrows('foo'));  // correctly does NOT throw, test passes

  // The goal: assert that an async function taking a parameter and awaiting, throws
  
  // Can't use assertRejects below due to error Leaks detected:
  // -  "fetchCancelHandle" was created during the test, but not cleaned up during the test. Close the resource before the end of the test.
  // - An async operation to send a HTTP request was started in this test, but never completed. This is often caused by not awaiting the result of a `fetch` call.
  /** But {@link asyncFuncThatAwaitsAndThrows} did await the fetch! */
  assertRejects(() => asyncFuncThatAwaitsAndThrows('text'));  // <-- BUG?
  
  // await asyncFuncThatAwaitsAndThrows('text');  // correctly throws (sanity check)
  
  // Comment the last assertRejects() call above, and uncomment the assertThrows line below
  // "error: AssertionError: Expected function to throw."
  assertThrows(async () => await asyncFuncThatAwaitsAndThrows('text'));  // <-- BUG?
});
```

**Environment**

- OS: Fedora Linux
- deno version: 2.1.3
- @std/assert version: 1.0.9

**Comment by BlackAsLight** [comment]
You need to `await assertRejects(`

**Comment by dandv** [comment]
Thank you for the clarification @BlackAsLight. After adding that await, I get the same error as from the next statement, `assertThrows(async () => await asyncFuncThatAwaitsAndThrows('text'));`:

> error: AssertionError: Expected function to throw.

 But I believe the assertThrows statement should succeed, because `asyncFuncThatAwaitsAndThrows('text')` does throw. Maybe I'm missing something else here?

**Comment by BlackAsLight** [comment]
`assertRejects` expects a function that returns a promise to reject. `assertThrows` expects a non-async non-promise returning function to throw.

**Comment by dandv** [comment]
So `assertRejects` was the right track, but I had to await it, **and** consume the response body to prevent that leak. This works; is it the recommended structure?

```ts
import { assertRejects } from '@std/assert'

async function asyncFuncThatAwaitsAndThrows(format = 'json') {
  const res = await fetch(`https://api.ipify.org?format=${format}`);
  await res.text();  // consume the response body to prevent resource leaks
  throw new Error('This async function awaited and had to throw');
}

Deno.test('asyncFuncThatAwaitsAndThrows should throw', async () => {
  await assertRejects(async () => await asyncFuncThatAwaitsAndThrows('json'));
});
```

**Comment by BlackAsLight** [comment]
I don't know what you mean by consume, but the code you have here is correct. To not have a leak you need to have all promises created in the test either resolved or rejected before the test returns. If there is any promises still hanging around in the event loop from the test then that's considered a leak.
