### ISSUE TITLE
@std/fmt/duration singularize words when the value === 1

### ISSUE THREAD

**Issue by GriffinJohnston** [denoland/std#6293]
Currently the full unit words (seconds, minutes, hours, etc) are plural in all cases, even when the number is 1. It seems fairly simple to only pluralize when the number != 1, which would produce more idiomatic, grammatically correct English phrases ( "1 minute" vs "1 minutes"). Since I believe that's the point of the `style: "full"` setting, this seems like a worthwhile update.

Perhaps there's some complexity there I haven't considered, but I've created a quick PR to show how it might be done. Happy to discuss.

**Comment by timreichen** [comment]
This would also be aligned with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat
